
import type { NextPage } from "next";
import Head from "next/head";
import FriendList from "../../components/Friend/FriendList";
import Header from "../../components/Header";
import { useAppContext } from "../../context/State";

const people = [
  {
    name: "Jane Cooper",
    title: "Paradigm Representative",
    role: "Admin",
    email: "janecooper@example.com",
    telephone: "+1-202-555-0170",
    imageUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
  },
  // More people...
];

const Friend: NextPage = () => {
  const sharedState = useAppContext();
  return ( sharedState.authenticated() &&
    <div>
      <Head>
        <title>FINE | Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="dark:bg-gray-700 min-h-screen">
        <main className="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8 py-8">
          <ul className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            {people.map((person) => (
              <FriendList person={person} 
              key={person.email}/>
            ))}
          </ul>
        </main>
      </div>
    </div>
  );
};

export default Friend;
