import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>FINE | Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="dark:bg-gray-700 min-h-screen">
        <main className="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8 py-8">
          <div className='flex flex-col-reverse sm:flex-row gap-4 justify-center items-center mx-auto py-8 sm:w-3/4 bg-indigo-200 rounded'>
            <div className='flex flex-col w-3/4 sm:w-1/2 justify-center p-4 gap-4'>
              <span className='font-bold text-3xl'>Simple. Secure. Reliable messaging</span>
              <span>With WhatsApp, you'll get fast, simple, secure messaging and calling for free*, available on phones all over the world.</span>
            </div>
            {/* <div className='relative w-48 h-96'>
              <Image
                  src="/home/WA Chat Image.png"
                  layout="fill"
              />
            </div> */}
            <img src="/images/home/WA Chat Image.png" className='w-48 h-96' alt="" />
          </div>
        </main>
      </div>
    </div>
  )
}

export default Home
